apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: coordinator-instances
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230711
  machineType: c5.xlarge
  maxSize: MAX_DUMMY
  minSize: MIN_DUMMY
  rootVolumeSize: 32
  role: Node
  nodeLabels:
    role: coordinator
  subnets:
    - us-east-1a
